<?php  
  echo $_ENV['OPENSHIFT_MYSQL_DB_HOST'];
  //echo $_ENV['OPENSHIFT_MYSQL_DB_USERNAME'];
  //echo $_ENV['OPENSHIFT_MYSQL_DB_PASSWORD'];
  //echo $_ENV['OPENSHIFT_APP_NAME'];
  //echo $_ENV['OPENSHIFT_MYSQL_DB_PORT'];
  //echo $_ENV['OPENSHIFT_MYSQL_DB_SOCKET'];
?>
